# fly.toml app configuration file generated for pop-pop-chaos on 2025-01-26T20:58:27+10:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pop-pop-chaos'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
